/**
 * Payment Engine — Core Interfaces
 * Root/Engine/src/payments/types.ts
 *
 * Contratos agnósticos que toda gateway deve implementar.
 * Adicionar nova gateway = criar providers/nova.ts + registrar no registry.ts.
 * Zero mudanças no roteador ou no core.
 */

// ─── DTOs ────────────────────────────────────────────────────

export interface CreateChargeDTO {
    /** Unique correlation ID generated by our engine (UUID) */
    correlationID: string
    /** Amount in cents — e.g. 10000 = R$100,00 */
    amount: number
    /** Human-readable description shown on the Pix receipt */
    comment?: string
}

// ─── Response Types ──────────────────────────────────────────

export interface ChargeResponse {
    /** Provider-side charge ID (Woovi's correlationID, Stripe's paymentIntent.id, etc.) */
    providerChargeId: string
    /** PIX BR Code (Copia e Cola) — null for non-Pix providers */
    brCode: string | null
    /** Initial status as returned by the provider */
    status: string
    /** Raw provider response for debugging / audit trail */
    raw: unknown
}

export interface WebhookEvent {
    /** Normalised event type — our engine's vocabulary */
    type: 'CHARGE_COMPLETED' | 'CHARGE_FAILED' | 'UNKNOWN'
    /** Provider-side charge ID to look up in tenant_charges */
    providerChargeId: string
    /** Raw webhook body for audit */
    raw: unknown
}

// ─── Provider Interface ──────────────────────────────────────

/**
 * Every payment gateway adapter must implement this interface.
 * The `appId` parameter carries the provider-specific credential
 * (OpenPix App ID, Stripe Secret Key, etc.) injected at call time
 * from c.env to keep providers stateless and testable.
 */
export interface PaymentProvider {
    createCharge(dto: CreateChargeDTO, appId: string): Promise<ChargeResponse>
    parseWebhook(body: unknown): Promise<WebhookEvent>
}
